name: phone_number_input_fromscratch
description: Flutter app


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <=3.5.4"


dependencies:
  flutter:
    sdk: flutter
  mask_text_input_formatter: ^2.9.0
  provider: ^6.1.2
  http: ^1.2.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_svg: ^2.0.16
  google_fonts: ^6.2.1
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - images/search_icon.svg

