name: phone_number_input_fromscratch
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  mask_text_input_formatter: ^2.4.0
  provider: ^6.0.4
  http: ^0.13.5
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_svg: ^1.1.5
  google_fonts: ^3.0.1
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - images/search_icon.svg

